### ISSUE TITLE
Noise when recording voice in Safari browser

### ISSUE THREAD

**Issue by MarinescuEvghenii** [ai/audio-recorder-polyfill#17] opened 2018-10-12 12:36 UTC
I'm able to record the audio in Safari Version 12.0 (13606.2.11) Mac OSX High Sierra, but the recorded sound is distorted. Here is the example https://goo.gl/2xY8tp. Do you know anything about this issue?

Thanks.

**Comment by ai** [comment] 2018-10-12 15:47
Have no idea, sorry.

**Comment by harwee** [comment] 2018-11-02 11:31
@MarinescuEvghenii were you able to solve this problem? I am facing the same.

**Comment by ai** [comment] 2018-11-02 16:31
@harwee interesting. Can you make PR?

**Comment by nicolocarpignoli** [comment] 2019-01-18 11:11
I can confirm that stream.clone() fix this

**Comment by ai** [comment] 2019-01-18 19:04
@nicolocarpignoli do you want to send PR if you already changed the sources?

**Comment by harwee** [comment] 2019-01-20 17:34
@ai  can you make a pull request, I tried making one but since i am not a JS developer I coudn't write test cases for this change 😞

**Comment by ai** [comment] 2019-01-20 17:37
@harwee you can send PR without tests (it is OK for browser compatibility fixes)

**Comment by ai** [comment] 2019-02-05 18:09
the fix released in 0.1.4

**Closed** 2019-02-10 21:19 UTC
